# Generated by Django 3.2.5 on 2021-07-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
